// Simulation Mode Vocabulary - maps spiritual terms to simulation/code terminology

export const SIM_VOCAB: Record<string, string> = {
  // Core concepts
  'Angel Number': 'Anomaly Code',
  'angel number': 'anomaly code',
  'Angel Numbers': 'Anomaly Codes',
  'angel numbers': 'anomaly codes',
  'Log a Number': 'Report a Glitch',
  'log a number': 'report a glitch',
  'Soul Twin': 'Signal Match',
  'soul twin': 'signal match',
  'Soul Twins': 'Signal Matches',
  'Oracle': 'The Architect',
  'oracle': 'the architect',
  'Dream Journal': 'Memory Cache',
  'dream journal': 'memory cache',
  'Dreams': 'Memory Fragments',
  'dreams': 'memory fragments',
  'Cosmic Feed': 'System Broadcast',
  'cosmic feed': 'system broadcast',
  'Feed': 'Broadcast',
  'Profile': 'Identity Matrix',
  'profile': 'identity matrix',
  'Healing Hub': 'System Repair',
  'Badges': 'Clearance Levels',
  'badges': 'clearance levels',
  'Streak': 'Uptime',
  'streak': 'uptime',
  'Messages': 'Secure Channel',
  'messages': 'secure channel',
  'Journal': 'Memory Cache',
  'journal': 'memory cache',
  'Numerology': 'Code Analysis',
  'numerology': 'code analysis',
  'Cosmic': 'Digital',
  'cosmic': 'digital',
  'Spiritual': 'Systemic',
  'spiritual': 'systemic',
  'Synchronicity': 'Causality Loop',
  'synchronicity': 'causality loop',
  'Manifestation': 'Execution',
  'manifestation': 'execution',
  'Affirmations': 'Directives',
  'affirmations': 'directives',
  'Chakras': 'Energy Nodes',
  'chakras': 'energy nodes',
  'Crystals': 'Data Cores',
  'crystals': 'data cores',
  'Rituals': 'Protocols',
  'rituals': 'protocols',
  'Meditations': 'Defragmentation',
  'meditations': 'defragmentation',
  'Tarot': 'Probability Matrix',
  'tarot': 'probability matrix',
  'Compatibility': 'Signal Resonance',
  'compatibility': 'signal resonance',
  'Insights': 'System Logs',
  'insights': 'system logs',
  'Statistics': 'Data Output',
  'statistics': 'data output',
  'Timeline': 'Process History',
  'timeline': 'process history',
  'Calendar': 'Cycle Tracker',
  'calendar': 'cycle tracker',
  'Synthesis': 'Core Analysis',
  'synthesis': 'core analysis',
  'Breathwork': 'CPU Reset',
  'Solfeggio': 'Frequency Calibration',
  'Moon Phases': 'Cycle Monitor',
  'Notifications': 'System Alerts',
  'Settings': 'Configuration',
  'Upgrade': 'Access Level',
  'Home': 'Terminal',
  'Explore': 'Utilities',
  'Healer': 'System Technician',
  'healer': 'system technician',
  'Saved': 'Archived',
  'Dictionary': 'Code Reference',
  // Nav labels
  'Deep Numerology': 'Deep Code Analysis',
  'Personal Year': 'Annual Cycle',
  'Karmic Debt': 'Debt Subroutine',
  'Soul Twin Radar': 'Signal Scanner',
  'Vision Board': 'Reality Compiler',
  'Cosmic Weather': 'System Status',
}

// Nav items for simulation mode
export const SIM_NAV: Record<string, string> = {
  'Home': 'TERMINAL',
  'Journal': 'MEMORY',
  'Explore': 'UTILS',
  'Feed': 'BROADCAST',
  'Messages': 'COMMS',
  'Profile': 'IDENTITY',
}

export function simVocab(text: string): string {
  return SIM_VOCAB[text] || text
}
